#ifndef LOGANDRECORDEXP_GLOBAL_H
#define LOGANDRECORDEXP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LOGANDRECORDEXP_LIBRARY)
#  define LOGANDRECORDEXPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LOGANDRECORDEXPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif
